// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Implicit flow (ne PKCE): potvrzovací/reset odkazy nesou tokeny přímo v URL
    // a fungují na JAKÉMKOLIV zařízení/prohlížeči. PKCE vázal potvrzení na zařízení,
    // kde registrace začala (code verifier v localStorage) → odkaz pak zákazníkovi
    // na jiném zařízení/prohlížeči (nebo po přeskenování e-mailem) spadl s chybou.
    flowType: 'implicit',
  }
});